### ISSUE TITLE
Translate Patreon page in english

### ISSUE THREAD

**Issue by jerembdn** [onRuntime/onruntime-website#28]
Voici les textes à traduire en Anglais (Envoie les traductions en commentaire sous ce ticket) :
![image](https://user-images.githubusercontent.com/37664500/153724526-ceeaf17b-5179-4251-ae4f-b041b56f5e3b.png)
![image](https://user-images.githubusercontent.com/37664500/153724537-f2e595db-3222-4c5b-acae-532af1c53205.png)

Je te laisse libre recours @YounesBessa d'améliorer ce que tu veux, et même rajouter de nouvelles idées.

**Comment by YounesBessa** [comment]
@jerembdn 
Get a front row seat to the studio's activity! With this tier, you get exclusive perks such as early access to our applications, VIP tickets to our private events, and much more!

remplace aussi "in our private events" par "to our private events" dans la liste en dessous de la description dans le premier screen

onRuntime Studio can start to expand and launch a recruitment campaign
